### ISSUE TITLE
Null pointer exception on clicking on items in recycler view

### ISSUE THREAD

**Issue by ghost** [msayanece/EasyListView#1]
I have not used the method "setOnItemClickListener" and when I click on any item it craches.

java.lang.NullPointerException: Attempt to invoke interface method 'void com.sayan.easylistwidget.EasyListView$OnItemClickListener.onClick(android.view.View, int)' on a null object reference
        at com.sayan.easylistwidget.adapters.CustomRecyclerAdapter$2.onClick(CustomRecyclerAdapter.java:69)

**Comment by msayanece** [comment]
Thanks for the contribution. I have done the necessary changes in the new release.
